version: '3.3'

services:
  namenode:
    build: ./namenode
    ports:
      - "9000:9000"
      - "50070:50070"
    hostname: hdfs-namenode

  datanode:
    build: ./datanode
    ports:
      - "50075:50075"
      - "50010:50010"
    hostname: localhost
    depends_on:
      - namenode 
    links:
      - namenode:hdfs-namenode
