version: '3.3'

services:
  namenode:
    build: ./namenode
    ports:
      - "9000:9000"
      - "50070:50070"
    hostname: namenode

  resourcemanager:
    build: ./resourcemanager
    ports:
      - "8088:8088"
      - "8031:8031"
    hostname: resourcemanager

  datanode:
    build: ./datanode
    ports:
      - "50075:50075"
      - "50010:50010"
    hostname: localhost
    depends_on:
      - namenode
    links:
      - namenode

  nodemanager:
    build: ./nodemanager
    ports: 
      - "8042:8042"
    depends_on:
      - resourcemanager
