ARG JAVA_VERSION=8
FROM java:${JAVA_VERSION}

ARG HADOOP_VERSION=2.9.0
ARG BASE_PATH=/opt
ARG DATA_PATH=/data/hdfs

ENV HADOOP_PREFIX=${BASE_PATH}/hadoop-${HADOOP_VERSION}
ENV HADOOP_CONF_DIR=${HADOOP_PREFIX}/conf/

RUN mkdir -p ${HADOOP_PREFIX} && \
	mkdir -p ${DATA_PATH}

RUN curl -o ${HADOOP_PREFIX}.tar.gz http://apache.cu.be/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
	tar -zxvf ${HADOOP_PREFIX}.tar.gz -C ${BASE_PATH} && \
	rm ${HADOOP_PREFIX}.tar.gz

# TODO: remove the parts we don't need!!!
RUN rm -rf ${HADOOP_PREFIX}/etc

ENV HADOOP_ROOT_LOGGER="INFO,RFA"