ARG JAVA_VERSION=8
FROM java:${JAVA_VERSION}

ARG HADOOP_VERSION=2.9.0
ARG BASE_PATH=/opt
ARG DATA_PATH=/data/hdfs

ENV HADOOP_PATH=${BASE_PATH}/hadoop-${HADOOP_VERSION}

RUN mkdir -p ${HADOOP_PATH} && mkdir -p ${DATA_PATH}

RUN curl -o ${HADOOP_PATH}.tar.gz http://apache.cu.be/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
	tar -zxvf ${HADOOP_PATH}.tar.gz -C ${BASE_PATH} && \
	rm ${HADOOP_PATH}.tar.gz

# TODO: remove the parts we don't need!!!
RUN rm ${HADOOP_PATH}/etc/hadoop/*